# -*- coding: utf-8 -*-
"""TASK 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ko53NQsjM2KlqONHQqqpzf9X-gXgHLcU

1.Given a list l=[23, 45, 25 ,78, 90, 45, 22, 56, 99, 12, 9, 75, 32]

Write a single line program to display.

a) elements at even index in the list.

b) remove the 3 middle elements (45, 22 and 56)
"""

#please write the code below this line
l=[23,45,25,78,90,45,22,56,99,12,9,75,32]
print("The elements at even indexes are ",l[1],l[3],l[5],l[7],l[9],l[11],)

#please write the code below this line
l=[23,45,25,78,90,45,22,56,99,12,9,75,32]
a,b,c=l.pop(5),l.pop(6),l.pop(7)
print(a,b,c)

"""2.Given a list lowerCase=['a', 'e', 'i', 'o', 'u']
Create a new list upperCase using list comprehension and copy the content of the lowerCase list, but in uppercase (capital letters). (upperCase should be ['A', 'E', 'I', 'O', 'U'])
"""

#please write the code below this line
lowerCase=['a', 'e', 'i', 'o', 'u']
upperCase = [x.upper() for x in lowerCase ]

"""3.Given a tuple fruits = ("banana", "cherry", "apple", "grapes")
Create 3 variables yellow, red and green and assign them with fruits of their respective color.
(yellow="banana", red=["cherry", "apple"], green="grapes (hint- Use unpacking)
"""

#please write the code below this line
fruits = ("banana", "cherry", "apple", "grapes") 
yellow,red,green = ("banana",["cherry","apple"],"grapes")