# -*- coding: utf-8 -*-
"""TASK 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aXEjfzp0KUysl_wbhGZYYfUp9LxIlhhV

1 - Write a program which takes a number as input from the user and check whether the number is odd or even.If odd print the number is odd if not print it is even.
"""

#please enter your answer below this line
x=int(input("Enter a number"))
if x%2==0:
	print("Even")
else:
	print("Odd")

"""2 -Write a program to find the largest among three numbers and print the largest number."""

#please enter your answer below this line
x=int(input("Enter first number"))
y=int(input("Enter second number"))
z=int(input("Enter third number"))
if (x>y and x>z):
	print(x ,"is the largest number")
elif (y>z and x<z):
	print(z,"is the largest number")
elif y>z:
	print(y ,"is the largest number")
else:
	print(z,"is the largest number")

"""3 -Write a function to prompt for a score between 0.0 and 1.0.

    If the score is out of range, print an error.
    If the score is between 0.0 and 1.0, print a grade using the following table:
    Score Grade
             Score	Grade
            >= 0.9	A
            >= 0.8	B
            >= 0.7	C
            >= 0.6	D
             < 0.6	F
If the user enters a value out of range, print a suitable error message and exit. For the test, enter a score of 0.85.
"""

#please enter your answer below this line
x=float(input("Enter a score between 0.0 and 1.0"))
if x>=0.9 and x<=1.0:
	print("A Grade")
elif x>=0.8 and x<0.9:
	print("B Grade")
elif x>=0.7 and x<0.8:
	print("C Grade")
elif x>=0.6 and x<0.7:
    print("D Grade")
elif x<0.6:
    print("F Grade")
else:
    print("Error: please enter a number from the above given range ")